#!/bin/bash
trap '' 0 1 2 9 15

nh= _
nrad=_
ncopy=_

for (( h=0; h < $nrad; h++ ))
do
    for (( r=0; r < $nrad; r++ ))
    do
    	for (( c=0; c < ${ncopy}; c++ ))
    	do
            resf0="results/result_h"
            resf1='_r'
            resf2='_c'

    	    result_file=${resf0}${h}${resf1}${r}${resf2}${c};

    	    if ! [ -f "${result_file}" ]; then
                command0="sbatch -n1 -t240 --wrap='srun ./calcV "
                sep=" "
                command2="'"
    	        command=${command0}${h}${sep}${r}${sep}${c}${command2};
    	        echo "$command";
                echo "$command" >> temp
    	    fi
    	done;
    done;
done;

chmod 777 temp
./temp
rm temp