#!/bin/bash
trap '' 0 1 2 9 15

nh= _
nrad=_
ncopy=_
for (( i=0; i<$nrad; i++ ))
do
	for (( j=0; j<$ncopy; j++ ))
	do	
		a="sbatch -n 1 -t 240 --wrap='srun ./calcV "
		b="'"
		c=" " 
		d=$a$i$c$j$b
		e="results/result_"
		f="_"
		g=".txt"
		file_result=$e$i$f$j$g
		if ! [ -f "$file_result" ]; then
			echo "$d" >> temp
		fi
	done;
done;

for (( h=0; h < $nrad; h++ ))
do
    for (( r=0; r < $nrad; r++ ))
    do
    	for (( c=0; c < ${ncopy}; c++ ))
    	do
            resf0="results/result_h"
            resf1='_r'
            resf2='_c'

    	    result_file=${resf0}${h}${resf1}${r}${resf2}${c};

    	    if ! [ -f "${result_file}" ]; then
    	    sbatch -n1 -t240 --wrap='srun ./calcV ${h} ${r} ${c}';
    	    echo "$i";
    	    fi
    	done;
    done;
done;

